version: '3.5'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: retailOrders_API
    build:
      context: .
      dockerfile: src/Dockerfile
    links:
      - db
    depends_on:
      - db
    networks:
      - retailOrdersNet

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: retailOrders_MSSQL
    networks:
      - retailOrdersNet

networks:
    retailOrdersNet:
      driver: bridge
      name: retailOrdersNet