version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Dockerfile
    networks:
      - retail-orders-net
    links:
      - db
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: retail-orders-mssql
    networks:
      - retail-orders-net
networks:
    retail-orders-net:
        driver: bridge